import { Inter } from 'next/font/google'

import { ModalProvider } from '@/components/providers/ModalProvider'

import type { Metadata } from 'next'

import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Providers from '@/components/providers'
import { ruRU } from '@clerk/localizations'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Панель администратора',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <ClerkProvider localization={ruRU}>
        <html lang="en">
          <body className={inter.className}>
            <Providers>
              <ModalProvider />
              {children}
            </Providers>
          </body>
        </html>
      </ClerkProvider>
  )
}
